name: Bug Report
description: File a bug or crash report
title: "Please write an informative title describing the bug in a few words"
labels: ["Type: bug", "Status: to verify"]
body:
  - type: markdown
    attributes:
      value: |
        # This is not the official Nitrox repository. (This is the repository of the cracked Mod)
        ## Before opening an issue, check the FAQ to see if your problem is there.
        
  - type: dropdown
    id: nitrox_version
    attributes:
      label: Are you on the latest version of Nitrox Cracked Mod?
      description: If not, you should try updating first.
      options:
        - Yes, I'm on the latest release of Nitrox Cracked Mod.
        - No, I need to download a newer version and try again.
    validations:
      required: true
  - type: textarea
    id: game_version
    attributes:
      label: What version of Subnautica are you using?
      description: The game version is located at the top right in the main menu of the game.
      placeholder:  For example mar.-2023 71288
    validations:
      required: true
  - type: textarea
    id: what_happened
    attributes:
      label: Describe the issue.
      description: What happened? Should something else have happened instead?
      placeholder: Tell us what you saw! 
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Describe the steps you took to encounter the bug.
      description: How did it happen? Please provide steps to reproduce the bug if possible. Did the bug disappear with slightly altered steps?
      placeholder: Tell us what you did! 
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please upload your game logs if possible. The logs are located next to the launcher in a folder called "Nitrox Logs".
        Upload the most recent "game-XXXXXXXX.log" and if you hosted the server also "server-XXXXXXXX.log" to [Pastebin](https://pastebin.com/).
        After you created a paste for both files post their links into this box.
      placeholder: |
        For example:
        Game: https://pastebin.com/qFxU2dz7
        Server: https://pastebin.com/X4tBdE2R
    validations:
      required: false